Repository nirbhaykumar7808/nirbhaykumar7808, pull requests merged in 2022-10, with the labels that each got.

#1 Create Greaterelments.cpp
  Greaterelments.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#3 largestelement.cpp
  largestelement.cpp
  rearrange_array.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#5 largest no in the array
  largestelement.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#9 Create print hello world
  print hello world
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#8 find length of string using stl
  length of string using stl
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#7 Create duplicate no in array
  duplicate no in array
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#6 Create reverse string
  reverse string
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#10 Encapsulation.cpp
  Encapsulation.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#14 SpaceInvaders.py
  SpaceInvaders.py
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#11 Inheritance.cpp
  Inheritance.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#13 Create Inlinefn.cpp
  Inlinefn.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#12 Create Polymorphism.cpp
  Polymorphism.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#17 Create d.cpp
  d.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#16 class.py
  class.py
  inheritance.py
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#15 Create dutchnationalflag.cpp
  dutchnationalflag.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#18 instance.py
  instance.py
  iteration.py
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#19 Nirbhaykumar780890 patch 1
  Graphbasic.cpp
  graph.py
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#20 plot.py
  plot.py
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#21 Create graphimplement.cpp
  graphimplement.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#22 Create Treetraversal.cpp
  Treetraversal.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#23 matplotlib_plot.py
  matplotlib_plot.py
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#24 Update Encapsulation.cpp
  Encapsulation.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#25 Update rearrange_array.cpp
  rearrange_array.cpp
Labels: enhancement, hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#26 Update zigzagarray.cpp
  zigzagarray.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#27 Update Graphbasic.cpp
  Graphbasic.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#28 Update largestelement.cpp
  largestelement.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#29 Create Kya.cpp
  Kya.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#38 Update graph.py
  graph.py
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#30 Create dijsktra.cpp
  dijsktra.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#31 Update Encapsulation.cpp
  Encapsulation.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#32 Update Graphbasic.cpp
  Graphbasic.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#33 Update Inheritance.cpp
  Inheritance.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#34 Update Greaterelments.cpp
  Greaterelments.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#35 Update Polymorphism.cpp
  Polymorphism.cpp
Labels: bug, good first issue, hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#36 Update SpaceInvaders.py
  SpaceInvaders.py
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#37 Update class.py
  class.py
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest

#39 Create Knight Tour Problem
  Knight Tour Problem
Labels: hacktoberfest2022, hacktoberfest-accepted, hacktoberfest
